version: "3.4"
services:
  consul:
    image: consul
    # a opção “-client 0.0.0.0” é necessária para habilitar a interface REST localmente
    # sem ela, o comando “consul members”, por exemplo, não funciona
    # https://stackoverflow.com/questions/35132687/how-to-access-externally-to-consul-ui
    # a opção “-ui” é necessária para habilitar a interface web externamente
    command: agent -server -bootstrap-expect=1 -ui -client 0.0.0.0
    volumes:
      - consul-data:/consul/data
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"training","server":true} 
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    ports:
      - "8500:8500"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - traefik

  traefik_init:
    image: traefik:1.7
    command:
      - "storeconfig"
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=example.com"
      - "--docker.watch"
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
      - "--logLevel=DEBUG"
      - "--accessLog"
      - "--debug"
      #- "--traefikLog.filePath='/tmp/logs/traefik.log'"
      #- "--accessLog.filePath='/tmp/logs/access.log'"
      #- "--acme"
      #- "--acme.storage=traefik/acme/account"
      #- "--acme.entryPoint=https"
      #- "--acme.httpChallenge.entryPoint=http"
      #- "--acme.onHostRule=true"
      #- "--acme.onDemand=false"
      #- "--acme.email=foobar@example.com"
    networks:
      - traefik
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - consul

  traefik:
    image: traefik:1.7
    depends_on:
      - traefik_init
      - consul
    command:
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway
      - traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  webgateway:
    driver: overlay
    # external: true
  traefik:
    driver: overlay

volumes:
  consul-data:
    # driver: [not local]

